config/routes.rb
Rails.application.routes.draw do
  get 'mypage', to: 'users#me'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :qas
  resources :users, only: %i[new create]
  get 'qas/index', to: 'qas#index'
  post 'qas/index', to: 'qas#index'
  patch "/qas" , to:'qas#index'
  patch "/qas/:id/edit", to:'qas#edit'
  patch "/qas/:id", to:'qas#update'
  delete 'qas/destroy', to: 'qas#destroy'
  post '/qas/new',to: 'qas#create'
  root 'answers#index'
  get 'answers/index',to: 'answers#index', as: :user_root
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/qa.rb
# == Schema Information
#
# Table name: qas
#
#  id          :bigint           not null, primary key
#  body        :text(65535)      not null
#  checkbox    :boolean
#  content     :text(65535)      not null
#  ingredients :text(65535)
#  name        :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Qa < ApplicationRecord
  belongs_to :user
  validates :body, presence: true, length: { maximum: 1000 }
  validates :content, presence: true, length: { maximum: 1000 }
  has_one :response
  
  def user
    return User.find_by(id: self.user_id)
  end

  def create
    qa = Qa.new(
      body: "1000-1000=?",
      content: "0",
      user_id: "1"
    )
  end  
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :bigint           not null, primary key
#  body       :text(65535)
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ApplicationRecord
  has_one :response
end

app/models/question_response_relation.rb
# == Schema Information
#
# Table name: question_response_relations
#
#  id          :bigint           not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  question_id :bigint
#  response_id :bigint
#
# Indexes
#
#  index_question_response_relations_on_question_id  (question_id)
#  index_question_response_relations_on_response_id  (response_id)
#
# Foreign Keys
#
#  fk_rails_...  (question_id => questions.id)
#  fk_rails_...  (response_id => responses.id)
#

class QuestionResponseRelation < ApplicationRecord
  belongs_to :question
  belongs_to :response
end

app/models/response.rb
# == Schema Information
#
# Table name: responses
#
#  id         :bigint           not null, primary key
#  body       :text(65535)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Response < ApplicationRecord
belongs_to :qa, optional: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  provider               :string(255)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  uid                    :string(255)
#  username               :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :qas, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]
         def self.from_omniauth(auth)
          find_or_create_by(provider: auth["provider"], uid: auth["uid"]) do |user|
            user.provider = auth["provider"]
            user.uid = auth["uid"]
            user.username = auth["info"]["nickname"]
            user.password = Devise.friendly_token[0,20]
            user.email = User.dumy_email(auth)
          end
        end
      
        def self.new_with_session(params, session)
          if session["devise.user_attributes"]
            new(session["devise.user_attributes"]) do |user|
              user.attributes = params
            end
          else
            super
          end
        end
        def password_required?
          super && provider.blank?
        end
      
        def email_required?
          super && provider.blank?
        end
        private
        def self.dumy_email(auth)
          "#{auth.uid}-#{auth.provider}@example.com"
        end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.from_omniauth(request.env["omniauth.auth"].except("extra"))

    if @user.persisted?
        flash.notice = "ログインしました！"
        sign_in_and_redirect @user
    else
      @user.skip_confirmation!
      @user.save!
        redirect_to new_user_registration_url
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/qas_controller.rb
class QasController < ApplicationController

  def index
    # @qa = current_user.qas.all
    # qas = current_user.qas.all
    
    gon.qas = Qa.all
    gon.user = current_user.id

    if params[:count] == nil
      qas = current_user.qas.all
      
      @sample = qas.sample(50)
      @count = 0

      gon.sample = @sample

      gon.count = @count
    else  
      sample = params[:sample]
      count = params[:count]
      qas = current_user.qas.all
      sample_array = []
      sample.each {|key, value|
        sample_id = value[:id]
        sample_array << qas.find(sample_id)
      }
      @sample = sample_array
      @count = count.to_i
    end 
    if @sample.blank?
      flash[:notice] = "問題を作成してください"
      redirect_to new_qa_path
    end  
  end  
  def new
    @qa = Qa.new
  end  

  def create
    @qa = Qa.new(qa_params)
    if @qa.save
      flash[:notice] = "作成しました"
      redirect_to action: :new
    else
      render "new"
    end  
  end  
  
  def show
  
  end  

  def edit
    @qa = Qa.find(params[:id])
  end  

  def update
    qa = Qa.find(params[:id])
    qa.update(qa_params) 
    redirect_back(fallback_location: qa_path)
  end  

  def destroy
     qa = Qa.find(params[:id])
     qa.delete

     redirect_to qas_path
  end  



  private
  def qa_params
    params.require(:qa).permit(:body, :content,  :name).merge(user_id: current_user.id)
  end  


end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def new
    
  end  

  def create


  end
  def destroy
  end  


  
end  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end  
  def create
    user = User.new(user_params)
    if user.save
      sign_in(user)
      session[:user_id] = user.id
      flash.notice = "ログインしました！"
      redirect_to root_path
    else
      redirect_to new_user_registration_path
    end  
  end  

  def me
    
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_footer.html.erb
<footer>
  <ul>
    <li><a href="#home">ホーム</a></li>
    <li><a href="#title1">おすすめ学習方法</a></li>
    <li><a href="#title3">アプリ使用方法</a></li>
  </ul> 
  <small> &copy; 2020 Study App</small>
</footer>

app/views/answers/_header.html.erb
<%= javascript_include_tag "answer.js" %>
<header class="home">
  <ul class="dropdwn">
        <li>Study App</li>
    <% if user_signed_in? %>
      <li><%= link_to "作成",new_qa_path %></li>
      <li><%= link_to "今日のタスク",qas_path%></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to '新規登録',new_user_registration_path %> </li>
      <li><%= link_to 'ログイン', new_user_session_path %>
        <ul class="dropdwn__menu">
          <li class="dropdwn__menu__1"><%= fa_icon("twitter" ) %><%=link_to "twitterでログインする",user_twitter_omniauth_authorize_path%></li>
          <li class="dropdwn__menu__2"><%= fa_icon("envelope")%><%= link_to "mailでログインする",new_user_session_path%></li>
        </ul>
      </li>  
      
    <% end %>
    </ul>
</header>

app/views/answers/_main.html.erb
<div class="content">
  <div class="content__main">
    <div class="content__title">
      <section>
          <h2 id="title1">
            1.分散学習方法！
          </h2>
          <p id="word">
            分散学習とは
            <br>
            科学的に推奨された学習方法であり
            <br>
            適切な時間間隔を開けて学習をすることです  
          </p>
      </section>
      <section>
        <h2 id="title2">
        2.想起学習方法！
        </h2>
        <p id="word2">最近の研究によると
          <br>
          思い出す作業を繰り返すことで
          <br>
          記憶の定着につながることが確認されています
        </p>
      </section>
      <section>
        <h2 id="title3">
          3.このアプリの使い方！
        </h2>
        <p id="word3">1.覚えたい内容の問題をテキスト欄に記入</p>
        <p id="word4">2.覚えたい内容の解答をテキスト欄に記入</p>
        <p id="word5">3.定期的に内容を復習</p>
      </section>
    </div>
    <div class="content__image">
      <%= image_tag asset_path('/answer.png'),class:'img',width:'700px',height:'500px'  %>
    </div>  
  </div>  
</div> 

app/views/answers/index.html.erb
<%= render partial: 'header'%>

<%= render partial: 'main'%>
<%= render partial: 'footer'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Study App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon(init: true) %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=620" >
    
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>


    <%= yield %>
  </body>
</html>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

app/views/qas/_response_form.html.erb
  
  <%= form_with model: @qa,:url => {:qas => :new},id: "new_qa", local: true do |f| %>
    <div class="submitn">
      <%= f.submit '作成', class: "submitn__btn"%>
          <%# <button type="submit" class="submitn__btn">作成</button> %>
    </div> 
    <% if @qa.errors.any? %>
      <div class="alert">
        <ul>
          <% @qa.errors.full_messages.each do |message| %>
            <li><%= message%></li>
            <% end %>
        </ul>
      </div>
    <% end%>
    <% if flash[:notice] %>
      <div class="message"><%= flash[:notice] %></div>
    <% end %>
    
  <div class="form">
      <div class="box1">
        <span class="form-name1">問題</span>
        <div class="form-question">
          <%= f.text_area :body, class: 'form__control',placeholder: "問題文", size: "40x20" %>
        </div>
      </div> 
      <div class="box2">
        <span class="form-name2">解答</span>

        <div class="form-answer">
          <%= f.text_area :content, class: 'form__aon',placeholder: "解答文", size: "40x20"%>
        </div>  
      </div>
  </div> 
  <% end %>  

app/views/qas/edit.html.erb
<div class="main-contents">
  <header id="create">
    <h1>問題編集</h1>
    <div class="top">
     <%= link_to '問題に戻る','/qas', class:"main__link__tag__name"%>
      
    </div>
  </header>
  
    <%= form_with model: @qa do |f| %>
    <div class="submitn">
      <%= f.submit '編集', class: "submitn__btn"%>
          <%# <button type="submit" class="submitn__btn">作成</button> %>
    </div> 

  <div class="form">
      <div class="box1">
        <span class="form-name1">問題</span>
        <div class="form-question">
          <%= f.text_area :body, class: 'form__control',placeholder: "問題文", size: "40x20" %>
        </div>
      </div> 
      <div class="box2">
        <span class="form-name2">解答</span>

        <div class="form-answer">
          <%= f.text_area :content, class: 'form__aon',placeholder: "解答文", size: "40x20"%>
        </div>  
      </div>
  </div> 
  <% end %>  
 
</div>

app/views/qas/index.html.erb
<%= javascript_include_tag "qa.js" %>
  <div class="main">
    <div class="main__name">  復  習　</div>
    <div class="main__link">
      <div class="main__link__tag">
        <ul>
          <li>
            <%= link_to '新規作成', qas_new_path,class:"main__link__tag__name"%>
            <%= link_to 'ホーム画面',root_path, class:"main__link__tag__name"%>
            <%= link_to '編集',edit_qa_path(@sample),class:"main__link__tag__name",id:"edit" %>
            <%= link_to '削除',qa_path( @sample), class:"main__link__tag__name",method: :delete %>
          <li>
        </ul>
      </div>
    </div>
    <div class="main__head">
      <div class="main__head__question" >
        <div id="question1">問題
        </div>
      </div>
      <div class="main__head__questions">

        <div class="main__head__questions__answer">
          
        </div>
      </div>
      
    </div>
    <div class="main__bootom">
      <div class="main__bootom__botun">
        <div id="main__bootom__botun__click">
          <%= form_with model: @sample,:url => {:qas => :index} do |f| %>
            <%= f.submit "解答を表示する",  class:"main__bootom__botun__click__function",id: "new_qa"%>
            <%= f.submit "次の問題へ", class:"main__bootom__botun__click__function__next",id: "next_qa"%>
          <% end %>
      </div>

      </div>
    </div>
  </div>
</div>

app/views/qas/new.html.erb
<div class="main-contents">
  <header id="create">
    <h1>問題作成</h1>
    <div class="top">
      <a href="/" class="top__btn">トップページに戻る</a>
    </div>
  </header>
    <%= render partial: 'response_form', locals:{ qa: @qa} %>
 
</div>

app/views/questions/new.html.erb
<div class="main-contents">
  <header id="create">
    <h1>問題作成</h1>
    <div class="top">
      <a href="/" class="top__btn">トップページに戻る</a>
    </div>
  </header>
  <%= form_with model: @question,:url => {:questions => :new} do |f| %>
    <div class="submitn">
      <%= f.submit '作成', class: "submitn__btn"%>
          <%# <button type="submit" class="submitn__btn">作成</button> %>
    </div>
  <div class="form">
      <div class="box1">
        <span class="form-name1">問題</span>
        <div class="form-question">
          <%= f.text_area :body, class: 'form__control',placeholder: "問題文", size: "40x20" %>
        </div>
      </div> 
  </div> 
    <%= render partial: 'response_form', locals:{ response: @response} %>
  <% end %>  
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>